package igu;

import java.util.List;
import logica.CargarPreguntas;

import javax.swing.JOptionPane;
import logica.Aspirante;
import logica.Pregunta;

public class PantallaRegistroAspirante extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaRegistroAspirante.class.getName());
    private static final java.util.List<Aspirante> lista_aspirantes = new java.util.ArrayList<>();

    CargarPreguntas preguntas = new CargarPreguntas();

    /**
     * Creates new form PantallaRegistroAspirante
     */
    public PantallaRegistroAspirante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombreAspirante = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtApellidoAspirante = new javax.swing.JTextPane();
        btnIniciarPrueba = new javax.swing.JButton();
        btnCancelarPrueba = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCedulaAspirante = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Aspirante");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ingresa tus datos para poder realizar la prueba");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Apellido:");

        txtNombreAspirante.setMaximumSize(new java.awt.Dimension(62, 20));
        txtNombreAspirante.setMinimumSize(new java.awt.Dimension(62, 20));
        jScrollPane1.setViewportView(txtNombreAspirante);

        jScrollPane2.setViewportView(txtApellidoAspirante);

        btnIniciarPrueba.setText("Iniciar Test");
        btnIniciarPrueba.addActionListener(this::btnIniciarPruebaActionPerformed);

        btnCancelarPrueba.setText("Cancelar Test");
        btnCancelarPrueba.addActionListener(this::btnCancelarPruebaActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cédula:");

        jScrollPane3.setViewportView(txtCedulaAspirante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciarPrueba)
                        .addGap(51, 51, 51)
                        .addComponent(btnCancelarPrueba))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane3)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarPrueba)
                    .addComponent(btnCancelarPrueba))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static List<Aspirante> getListaAspirantes() {
        return lista_aspirantes;
    }

    private void btnIniciarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPruebaActionPerformed

        this.setVisible(false); // Cerramos la ventana de registro por ahora
        evaluarAspirantes(); // Mostramos las preguntas y evaluamos a cada aspirante
    }//GEN-LAST:event_btnIniciarPruebaActionPerformed

    private void evaluarAspirantes() {

        boolean continuar = true;

        while (continuar) {

            // =============================
            // Registro del Aspirante
            // =============================
            // Se obtiene la información del formulario: nombre, apellido y cédula
            String nombre = txtNombreAspirante.getText().strip();
            String apellido = txtApellidoAspirante.getText().strip();
            String cedula = txtCedulaAspirante.getText().strip();

            // Validación de campos obligatorios
            if (nombre.isEmpty() || apellido.isEmpty() || cedula.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,
                        "Todos los campos de registro son obligatorios.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(true); // Vuelve a mostrar el formulario si falta información
                return;
            }

            // =============================
            // Inicialización del Examen
            // =============================
            // Se cargan las preguntas y se inicializan contadores de puntaje
            CargarPreguntas preguntas = new CargarPreguntas();

            int respuestas_correctas = 0;
            int respuestas_incorrectas = 0;
            int puntaje_total = 0;

            // =============================
            // Evaluación de Preguntas
            // =============================
            // Se recorre cada pregunta y se solicita respuesta al usuario
            int numero_pregunta = 1; // Para mostrar el número de pregunta correctamente
            
            for (Pregunta p : preguntas.lista_preguntas) {
                String respuesta;
                while (true) {
                    respuesta = JOptionPane.showInputDialog(
                            rootPane,
                            "Pregunta " + numero_pregunta + "/" + preguntas.lista_preguntas.size() + ":\n" + p.getPregunta(),
                            p.getTipo(),
                            JOptionPane.QUESTION_MESSAGE
                    );

                    // =============================
                    // Validación de Respuesta
                    // ============================
                    if (respuesta == null || respuesta.strip().isEmpty()) {
                        JOptionPane.showMessageDialog(rootPane,
                                "Debes ingresar una letra (A, B, C o D).",
                                "Información", JOptionPane.INFORMATION_MESSAGE);
                        continue;
                    }

                    if (respuesta.length() > 1) {
                        JOptionPane.showMessageDialog(rootPane,
                                "Solo se permite UNA letra.",
                                "Información", JOptionPane.INFORMATION_MESSAGE);
                        continue;
                    }

                    if (!respuestaValida(respuesta)) {
                        JOptionPane.showMessageDialog(rootPane,
                                "Letra inválida. Solo A, B, C o D.",
                                "Información", JOptionPane.INFORMATION_MESSAGE);
                        continue;
                    }

                    break; // Respuesta válida, salir del bucle
                }
                
                numero_pregunta++;

                p.setRespuestaUsuario(respuesta.charAt(0)); // Guardar respuesta del usuario

                // =============================
                // Conteo de puntaje
                // =============================
                if (p.esCorrecta()) {
                    respuestas_correctas++;
                } else {
                    respuestas_incorrectas++;
                }
                puntaje_total += calcularPuntajePregunta(p);// Suma puntos según tipo de pregunta
            }

            // =============================
            // Determinar Estatus
            // =============================
            // Si puntaje >= 71, se acepta; sino, se rechaza
            String estatus = (puntaje_total >= 71) ? "Aceptado" : "Rechazado";

            // =============================
            // Guardar Aspirante
            // =============================
            Aspirante aspirante = new Aspirante(nombre, apellido, cedula, puntaje_total, estatus);
            lista_aspirantes.add(aspirante);

            // =============================
            // Mostrar Resultados del Examen
            // =============================
            PantallaResultadoPrueba pantalla_resultado_prueba;
            pantalla_resultado_prueba = new PantallaResultadoPrueba(
                    nombre, apellido, cedula, respuestas_correctas,
                    respuestas_incorrectas, puntaje_total, estatus
            );

            pantalla_resultado_prueba.setVisible(true);
            pantalla_resultado_prueba.setLocationRelativeTo(null);

            // =============================
            // Preguntar si evaluar otro Aspirante
            // =============================
            int opcion = JOptionPane.showConfirmDialog(rootPane,
                    "¿Desea evaluar otro aspirante?",
                    "Continuar", JOptionPane.YES_NO_OPTION);

            continuar = (opcion == JOptionPane.YES_OPTION);

            if (continuar) {
                pantalla_resultado_prueba.dispose(); // Cierra la ventana anterior
                limpiarCamposRegistro(); // Limpia campos para nuevo registro
                this.setVisible(true);   // Muestra formulario para nuevo aspirante
            } else {
                // =============================
                // Mostrar Recopilación Final
                // =============================
                new RecopilacionDeResultadosAspirantes().mostrarRecopilacionDeResultadosAspirantes();
            }

        } // Fin del while
    }

    private boolean respuestaValida(String respuesta) {

        char[] respuestas_permitidas = {'a', 'b', 'c', 'd'};

        char letra = respuesta.toLowerCase().charAt(0);

        for (char c : respuestas_permitidas) {
            if (c == letra) {
                return true;
            }
        }

        return false;

    }

    private int calcularPuntajePregunta(Pregunta p) {
        if (!p.esCorrecta()) {
            return 0;
        }

        if (p.getTipo().startsWith("T")) {
            return 6; // Tecnología
        } else {
            return 4; // inglés o matemáticas
        }
    }

    private void limpiarCamposRegistro() {
        this.txtNombreAspirante.setText("");
        this.txtApellidoAspirante.setText("");
        this.txtCedulaAspirante.setText("");
    }

    private void btnCancelarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPruebaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarPruebaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void mostrarPantallaRegistroAspirante() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        PantallaRegistroAspirante pantalla_registro_aspirante = new PantallaRegistroAspirante();
        pantalla_registro_aspirante.setVisible(true);
        pantalla_registro_aspirante.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPrueba;
    private javax.swing.JButton btnIniciarPrueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txtApellidoAspirante;
    private javax.swing.JTextPane txtCedulaAspirante;
    private javax.swing.JTextPane txtNombreAspirante;
    // End of variables declaration//GEN-END:variables
}
