package igu;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.Aspirante;

public class RecopilacionDeResultadosAspirantes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecopilacionDeResultadosAspirantes.class.getName());

    /**
     * Creates new form RecopilacionDeResultadosAspirantes
     */
    public RecopilacionDeResultadosAspirantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultadosAspirantes = new javax.swing.JTable();
        salirDeResultados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("I.S.I.P. 2025 - Recopilación de Resultados");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("I.S.I.P. RESULTADOS FINALES DE ASPIRANTES");

        tablaResultadosAspirantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Nombre", "Apellido", "Cédula", "Puntos", "Estatus"
            }
        ));
        jScrollPane1.setViewportView(tablaResultadosAspirantes);

        salirDeResultados.setText("Salir");
        salirDeResultados.addActionListener(this::salirDeResultadosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salirDeResultados)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salirDeResultados)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirDeResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirDeResultadosActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirDeResultadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void mostrarRecopilacionDeResultadosAspirantes () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        RecopilacionDeResultadosAspirantes recopi_result_aspirantes;
        recopi_result_aspirantes = new RecopilacionDeResultadosAspirantes();
        
        recopi_result_aspirantes.cargarDatosTabla(PantallaRegistroAspirante.getListaAspirantes());
        
        recopi_result_aspirantes.setVisible(true);
        recopi_result_aspirantes.setLocationRelativeTo(null);
    }
    
    public void cargarDatosTabla(List<Aspirante> lista_aspirantes){
        
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"No.", "Nombre", "Apellido", "Cédula", "Puntos", "Estatus"}, 0
        ){
            @Override
            public boolean isCellEditable(int row, int column){
                return false; //Solo lectura
            }
        
        };
        
        int numero = 1;
        for (Aspirante a : lista_aspirantes) {
            modelo.addRow(new Object[]{
                numero++,
                a.getNombre(),
                a.getApellido(),
                a.getCedula(),
                a.getPuntosObtenidos(),
                a.getEstatus(),
            });
        }
        tablaResultadosAspirantes.setModel(modelo);
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salirDeResultados;
    private javax.swing.JTable tablaResultadosAspirantes;
    // End of variables declaration//GEN-END:variables
}
